ComidaIbero/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.pickupibero.urls")),
]

apps/pickupibero/forms.py
from django import forms
from django.contrib.auth import authenticate

class customLoginForm(forms.Form):
    ncuenta = forms.IntegerField()
    digitov = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

templates/login/login.html
{% extends "base.html" %}
{% load static %}

{% block htmlhead %}
    <link rel="stylesheet" href="{% static "css/login.css" %}">
{% endblock htmlhead %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="text-center">
                <h2>Inicio de Sesión</h2>
            </div>
            <div class="login-box">
                <form method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Número de Cuenta</label>
                        <div class="d-flex" id="username">
                            <input type="text" name="ncuenta" id="id_ncuenta" class="form-control" required/>
                            <span class="mx-2"> - </span>
                            <input type="text" name="digitov" id="id_digitov" class="form-control w-25" maxlength="1" required/>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Contraseña</label>
                        <input type="password" name="password" id="id_password" class="form-control" required/>
                    </div>
                    <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}